version: '3'

services:
  web:
    build:
      context: ./web  
    image: my-fast-api  
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - my_network

  database:
    build:
      context: ./database  
    image: my-mysql-image  
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - my_database_volume:/var/lib/mysql  
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
volumes:
  my_database_volume:  
    name: volume1_mysql