global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'web'
    static_configs:
      - targets: ['web:8080']  
  - job_name: 'database'
    static_configs:
      - targets: ['database:3306']  
